### ISSUE TITLE
Еrror

### ISSUE THREAD

**Issue by FPS-86** [Rsawyer2014/QB-Lottory-byDeadEndRP#1]
```
[   script:QB-Lottory] SCRIPT ERROR: @QB-Lottory/server.lua:42: attempt to index a nil value (field 'integer index')
[   script:QB-Lottory] > ref (@QB-Lottory/server.lua:42)
[   script:QB-Lottory] > <unknown> (@oxmysql/dist/build.js:21729)
[   script:QB-Lottory] > processTicksAndRejections (node:internal/process/task_queues:96)
[   script:QB-Lottory] > async rawQuery (@oxmysql/dist/build.js:21719)
```

**Comment by Rsawyer2014** [comment]
Did you add the one table to the server side lottery for the server to store its information? Let me know if that helps. I still need to add the line to the SQL file to automatically do it for you.

**Comment by FPS-86** [comment]
I have filled the SQL file into the database, but I did not understand the 2nd point. Where exactly (which file) should I register?

In qb-core/shared/items.lua, QB-Shops, I prescribed what was written. lotto.png threw where it is necessary

**Comment by Rsawyer2014** [comment]
Yeah you got to add the lotto item to the items.lua  in qb-core/shared/items.lua  I provided the item info in the readme, just copy and paste it into it than restart your server. If it still throws the SQL it may be due to the SQL update that came with the latest server build. If that fixes it or you keep getting the error let me know.

**Comment by FPS-86** [comment]
I did everything according to the instructions. But there is a problem with point 2

**Comment by Rsawyer2014** [comment]
What part?

**Comment by Rsawyer2014** [comment]
Ok, so after you import the SQL you'll get two tables lotto_tickets and lotto_server. In lotto server, insert an entry, there needs to be only one entry in the server table for it to store/save information to

**Comment by FPS-86** [comment]
problem solved

**Comment by FPS-86** [comment]
I did everything, but still the error remained

```
[   script:QB-Lottory] SCRIPT ERROR: @QB-Lottory/server.lua:41: attempt to perform arithmetic on a nil value (local 'oldpayout')
[   script:QB-Lottory] > ref (@QB-Lottory/server.lua:41)
[   script:QB-Lottory] > <unknown> (@oxmysql/dist/build.js:21729)
[   script:QB-Lottory] > processTicksAndRejections (node:internal/process/task_queues:96)
[   script:QB-Lottory] > async rawQuery (@oxmysql/dist/build.js:21719)
```


QBCore Framework latest version

**Comment by Rsawyer2014** [comment]
and when does this error happen? when you use the ticket? when you restart server? Ill try and replicate the issue.

**Comment by FPS-86** [comment]
![bandicam 2022-08-13 13-15-12-815](https://user-images.githubusercontent.com/21328410/184469630-6ad14897-69af-4d9b-a3b1-81228fdb16f5.jpg)

When starting the server, I SQL registered lotto.
Maybe I'm doing something wrong, I'm not too good at English.

**Comment by Rsawyer2014** [comment]
Run this SQL on your database


CREATE TABLE IF NOT EXISTS `LotteryTickets` (
`id` int(255) NOT NULL AUTO_INCREMENT,
`citizenid` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `LotteryServer` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `HasDrawn` varchar(10) DEFAULT NULL,
  `Payout` int(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `HasDrawn` (`HasDrawn`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

INSERT INTO `lotteryserver`(`id`, `HasDrawn`, `Payout`) VALUES ('1','false','500000')

**Comment by Rsawyer2014** [comment]
what are you using for a database? this was setup for XAMPP which could be problem

**Comment by FPS-86** [comment]
I am using MariaDB 10.4

**Comment by FPS-86** [comment]
New error

```
[   script:QB-Lottory] [   script:QB-Lottory] SCRIPT ERROR: @QB-Lottory/server.lua:62: attempt to index a nil value (field 'integer index')
[   script:QB-Lottory] > ref (@QB-Lottory/server.lua:62)
[   script:QB-Lottory] > <unknown> (@oxmysql/dist/build.js:21729)
[   script:QB-Lottory] > processTicksAndRejections (node:internal/process/task_queues:96)
[   script:QB-Lottory] > async rawQuery (@oxmysql/dist/build.js:21719)
```

**Comment by Rsawyer2014** [comment]
On server.lua line 41 change
local newPayout = oldpayout+value

To 

local newPayout = oldpayout+Config.TicketValue

Restart and retry. 

This script is first try at me trying to write lua with no help. Version is only 0.1.0 

I will continue to work on it and update to help fixes and get rid of errors

**Comment by FPS-86** [comment]
This error remained after the change:

`SCRIPT ERROR: @QB-Lottory/server.lua:62: attempt to index a nil value (field 'integer index')`

**Comment by Rsawyer2014** [comment]
Do you have any tickets submitted? Itll throw that error if theres no tickets in it because there is nothing to return the query with

**Comment by FPS-86** [comment]
Thanks for the help, but I've given up trying to run your resource on my server.
